# fly.toml app configuration file generated for rest-api-weathered-glitter-5232 on 2024-10-05T08:45:06Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'webtuitor-backend'
primary_region = 'ams'

[build]
  # Uncomment and specify if you are using a Dockerfile
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 3000  # Ensure your app listens on this port
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1  # Change to at least 1 to ensure availability
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
source = "uploads"
destination = "/uploads"

[env]
  PRODUCTION = true
  PROTOCOL = 'https'
  PORT = 3000  # Set PORT to match internal_port

